version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: ref-postgres15
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    volumes:
      - postgres:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always

  web:
    container_name: ref-web
    build: ../
    restart: always
    command: >
      /bin/sh -c "poetry run python manage.py migrate --noinput
      && poetry run python manage.py collectstatic --noinput
      && poetry run gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: ref-nginx
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static/
    depends_on:
      - web

volumes:
  static:
  postgres:
