# Generated by Django 4.2.4 on 2023-08-17 14:12

import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=12, region=None, unique=True, verbose_name="phone"
                    ),
                ),
                ("code", models.CharField(verbose_name="code")),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="created"
                    ),
                ),
            ],
            options={
                "verbose_name": "Код авторизации",
                "verbose_name_plural": "Коды авторизации",
                "ordering": ["-created"],
            },
        ),
    ]
